api/Events/urls.py
from django.urls import path
from .views import GetEventsAPIView


app_name = 'Events'

urlpatterns = [
    path('get_events/', GetEventsAPIView.as_view()),
]

api/Frontend/urls.py
from django.urls import path
from .views import *

app_name = 'frontend'

urlpatterns = [
    path('', ChooseLanguageView.as_view(), name='choose_language_view'),
    
    
    path('ru/type_order/', ChooseTypeOrderViewRU.as_view(), name='choose_type_order_view_ru'),
    path('ru/booking_table/', MainBookingTableViewRU.as_view(), name='events_and_dishes_booking_table_view_ru'),
    path('ru/booking_table/events/', EventsBookingTableViewRU.as_view(), name='events_booking_table_view_ru'),
    path('ru/booking_table/category/<category>/', CategoriesBookingTableViewRU.as_view(), name='categories_booking_table_view_ru'),
    path('ru/booking_table/cart/', CartBookingTableViewRU.as_view(), name='carts_booking_table_view_ru'),
    path('ru/booking_table/select_time/', SelectTimeForOrderBookingTableViewRU.as_view(), name='select_time_booking_table_view_ru'),
    path('ru/booking_table/select_place/', SelectPlaceForOrderBookingTableViewRU.as_view(), name='select_place_booking_table_view_ru'),
    path('ru/booking_table/select_quantity_of_people/', SelectQuantityOfPeopleBookingTableViewRU.as_view(), name='select_quantity_of_people_booking_table_view_ru'),
    
    
    path('ru/pickup/', MainPickupViewRU.as_view(), name='events_and_dishes_pickup_view_ru'),
    path('ru/pickup/events/', EventsPickupViewRU.as_view(), name='events_pickup_view_ru'),
    path('ru/pickup/category/<category>/', CategoriesPickupViewRU.as_view(), name='categories_pickup_view_ru'),
    path('ru/pickup/cart/', CartPickupViewRU.as_view(), name='carts_pickup_view_ru'),
    path('ru/pickup/select_time/', SelectTimeForOrderPickupViewRU.as_view(), name='select_time_pickup_view_ru'),
    
    
    path('ru/delivery/', MainDeliveryViewRU.as_view(), name='events_and_dishes_delivery_view_ru'),
    path('ru/delivery/events/', EventsDeliveryViewRU.as_view(), name='events_delivery_view_ru'),
    path('ru/delivery/category/<category>/', CategoriesDeliveryViewRU.as_view(), name='categories_delivery_view_ru'),
    path('ru/delivery/cart/', CartDeliveryViewRU.as_view(), name='carts_delivery_view_ru'),
    path('ru/delivery/get_geolocation/', GetGeolocationDeliveryViewRU.as_view(), name='get_geolocation_delivery_view_ru'),

    
    path('uz/booking_table/', MainBookingTableViewUZ.as_view(), name='events_and_dishes_booking_table_view_uz'),
    path('uz/type_order/', ChooseTypeOrderViewUZ.as_view(), name='choose_type_order_view_uz'),
    path('uz/booking_table/events/', EventsBookingTableViewUZ.as_view(), name='events_booking_table_view_uz'),
    path('uz/booking_table/category/<category>/', CategoriesBookingTableViewUZ.as_view(), name='categories_booking_table_view_uz'),
    path('uz/booking_table/cart/', CartBookingTableViewUZ.as_view(), name='carts_booking_table_view_uz'),
    path('uz/booking_table/select_time/', SelectTimeForOrderBookingTableViewUZ.as_view(), name='select_time_booking_table_view_uz'),
    path('uz/booking_table/select_place/', SelectPlaceForOrderBookingTableViewUZ.as_view(), name='select_place_booking_table_view_uz'),
    path('uz/booking_table/select_quantity_of_people/', SelectQuantityOfPeopleBookingTableViewUZ.as_view(), name='select_quantity_of_people_booking_table_view_uz'),

    path('uz/pickup/', MainPickupViewUZ.as_view(), name='events_and_dishes_pickup_view_uz'),
    path('uz/pickup/events/', EventsPickupViewUZ.as_view(), name='events_pickup_view_uz'),
    path('uz/pickup/category/<category>/', CategoriesPickupViewUZ.as_view(), name='categories_pickup_view_uz'),
    path('uz/pickup/cart/', CartPickupViewUZ.as_view(), name='carts_pickup_view_uz'),
    path('uz/pickup/select_time/', SelectTimeForOrderPickupViewUZ.as_view(), name='select_time_pickup_view_uz'),
    

    path('uz/delivery/', MainDeliveryViewUZ.as_view(), name='events_and_dishes_delivery_view_uz'),
    path('uz/delivery/events/', EventsDeliveryViewUZ.as_view(), name='events_delivery_view_uz'),
    path('uz/delivery/category/<category>/', CategoriesDeliveryViewUZ.as_view(), name='categories_delivery_view_uz'),
    path('uz/delivery/cart/', CartDeliveryViewUZ.as_view(), name='carts_delivery_view_uz'),
    path('uz/delivery/get_geolocation/', GetGeolocationDeliveryViewUZ.as_view(), name='get_geolocation_delivery_view_uz'),
]

api/config/urls.py
from django.contrib import admin
from django.urls import include, path
from config import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls', namespace='Categories')),
    path('orders/', include('orders.urls', namespace='Orders')),
    path('dishes/', include('dishes.urls', namespace='Dishes')),
    path('users/', include('users.urls', namespace='Users')),
    path('frontend/', include('frontend.urls', namespace='Frontend')),
    path('events/', include('events.urls', namespace='Events')),
    path('places/', include('places.urls', namespace='Places')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('frontend.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/users/urls.py
from django.urls import path

from .views import RegisterAPIView, LoginAPIView, \
    UserAPIView, UpdateUserAPIView, GetUserLanguageAPIView, \
    CheckManagerAPIView, GetUserByPkAPIView, GetManagersAPIView
    

app_name: str = 'users'

urlpatterns = [
    path('users/<telegram_pk>/', UserAPIView.as_view()),
    path('get_managers/', GetManagersAPIView.as_view()),
    path('register/', RegisterAPIView.as_view()),
    path('login/', LoginAPIView.as_view()),
    path('update/<telegram_pk>/', UpdateUserAPIView.as_view()),
    path('get_user_language/<telegram_pk>/', GetUserLanguageAPIView.as_view()),
    path('get_user_by_pk/<pk>/', GetUserByPkAPIView.as_view()),
    path('check_manager/<telegram_pk>/', CheckManagerAPIView.as_view()),
]

api/Events/models.py
from django.db import models
from django.utils.safestring import mark_safe


class Events(models.Model):
    """
    Model Events while month
    """
    image = models.ImageField(
        verbose_name='Фотокарточка'
    )
    description_ru = models.TextField(
        verbose_name='Описание RU'
    )
    description_uz = models.TextField(
        verbose_name='Описание UZ'
    )
    
    def descriptiontrim(self):
        return u"%s" % (self.description_ru[:35],) + '...'
    
    descriptiontrim.allow_tags = True
    descriptiontrim.short_description = 'Описание'
    
    def __str__(self) -> str:
        return self.image.url
    
    def __repr__(self) -> str:
        return super().__repr__()
    
    def img_preview(self): 
        return mark_safe(f'<img src="{self.image.url}" width="100px" height="75px"/>')
    
    img_preview.allow_tags = True
    img_preview.short_description = 'Миниатюра'

    class Meta:
        verbose_name = 'Эвент'
        verbose_name_plural = 'Эвенты'

api/Frontend/models.py
# Create your models here.

api/Events/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .models import Events
from .serializers import EventsSerializer


class GetEventsAPIView(APIView):
    """
    Get Events
    """
    serializer_class = EventsSerializer
    model = Events

    def get(self, request):
        events = self.model.objects.all()
        if events.exists():
            serializer = self.serializer_class(events, many=True)
            serialized_data = serializer.data
            return Response(data=serialized_data, status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_404_NOT_FOUND)

api/Frontend/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer


from events.models import Events
from events.serializers import EventsSerializer

from dishes.models import Dishes
from dishes.serializers import DishesSerializer

from categories.models import Categories
from categories.serializers import CategoriesSerializer

from places.models import Places
from places.serializers import PlacesSerializer


class ChooseLanguageView(APIView):
    """
    Choose Language View
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/choose_language.html'

    def get(self, request):
        return Response()


class ChooseTypeOrderViewRU(APIView):
    """
    Choose Type Order View RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/choose_type_order.html'

    def get(self, request):
        return Response()


class ChooseTypeOrderViewUZ(APIView):
    """
    Choose Type Order View UZ
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/uz/choose_type_order.html'

    def get(self, request):
        return Response()


# RU


# Booking Table with food



class MainBookingTableViewRU(APIView):
    """
    View Dishes RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/index.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.all()
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })


class EventsBookingTableViewRU(APIView):
    """
    View for Events 
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/events.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        return Response({
            'events': events_serializer.data,
        })


class CategoriesBookingTableViewRU(APIView):
    """
    View for categories RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/index.html'

    def get(self, request, category):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.filter(
            category=category
        )
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })


class SelectTimeForOrderBookingTableViewRU(APIView):
    """
    Select DateTime for order RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/select_time.html'

    def get(self, request):  
        return Response({})


class SelectPlaceForOrderBookingTableViewRU(APIView):
    """
    Select Place for order RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/select_place.html'

    def get(self, request):  
        places = Places.objects.filter(
            is_view=True
        )
        places_serializer = PlacesSerializer(places, many=True)

        return Response({
            'places': places_serializer.data,
        })
        

class CartBookingTableViewRU(APIView):
    """
    Cart view RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/cart.html'

    def get(self, request):  
        return Response({})
 

class SelectQuantityOfPeopleBookingTableViewRU(APIView):
    """
    Select quantity of people for order RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/booking_table/select_quantity_of_people.html'

    def get(self, request):  
        return Response({})


# Pickup


class MainPickupViewRU(APIView):
    """
    View Dishes RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/pickup/index.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.all()
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })


class EventsPickupViewRU(APIView):
    """
    View for Events 
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/pickup/events.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        return Response({
            'events': events_serializer.data,
        })


class CategoriesPickupViewRU(APIView):
    """
    View for categories RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/pickup/index.html'

    def get(self, request, category):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.filter(
            category=category
        )
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })


class SelectTimeForOrderPickupViewRU(APIView):
    """
    Select DateTime for order RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/pickup/select_time.html'

    def get(self, request):  
        return Response({})


class CartPickupViewRU(APIView):
    """
    Cart view RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/pickup/cart.html'

    def get(self, request):  
        return Response({})


# Delivery


class MainDeliveryViewRU(APIView):
    """
    View Dishes RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/delivery/index.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.all()
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })


class EventsDeliveryViewRU(APIView):
    """
    View for Events 
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/delivery/events.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        return Response({
            'events': events_serializer.data,
        })


class CategoriesDeliveryViewRU(APIView):
    """
    View for categories RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/delivery/index.html'

    def get(self, request, category):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.filter(
            category=category
        )
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })


class GetGeolocationDeliveryViewRU(APIView):
    """
    Select DateTime for order RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/delivery/get_geolocation.html'

    def get(self, request):  
        return Response({})


class CartDeliveryViewRU(APIView):
    """
    Cart view RU
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/ru/delivery/cart.html'

    def get(self, request):  
        return Response({})


# Uz


# Booking Table with food



class MainBookingTableViewUZ(APIView):
    """
    View Dishes UZ
    """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend/uz/booking_table/index.html'

    def get(self, request):
        events = Events.objects.all()
        events_serializer = EventsSerializer(events, many=True)

        dishes = Dishes.objects.all()
        dishes_serializer = DishesSerializer(dishes, many=True)

        categories = Categories.objects.all()
        categories_serializer = CategoriesSerializer(categories, many=True)

        return Response({
            'events': events_serializer.data,
            'dishes': dishes_serializer.data,
            'categories': categories_serializer.data,
        })

api/Frontend/templates/frontend/ru/pickup/cart.html
{% extends 'base.html' %}
{% load static %}

{% load static %} 
{% block title %} 
{{ title }} 
{% endblock title %}

{% block main %}

<div class="HeaderWrapper">
	<button class="BackButton" style="background: transparent; top: 40px; left: 20px; box-shadow: none;">
		<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;">
			<span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;">
			</span>
      <a href="{% url 'frontend:events_and_dishes_pickup_view_ru'  %}"><i class="fa-solid fa-chevron-left fa-lg"></i></a>
		</span>
	</button>   
	<h1>Корзина</h1>
	<div class="HeaderNone"><div style="width: 48px; height: 48px;"></div></div>
</div>

<div id="cartItemsList">
</div>


<div class="TextEmptyCart" style="visibility:hidden">
	<p class="Emodgi">🛒</p>
	Ваша Корзина Пуста 😅
</div>

<div>
	<div class="TextBlockWrapper">
		<div class="TextWrapper TextTotalPrice">
			<p class="TextTotalPriceP"></p>
		</div>
	</div>
  <a href="{% url 'frontend:select_time_pickup_view_ru'  %}">
		<div class="ButtonWrapperAcart">
			<div class="ButtonBlockWrappercart">
				<button class="ButtonWrappercart" style="width: 100%;height: 100%;">
					<div class="ButtonWrapperDivcart"><p class="TextButtonWrapper TextButtonWrapperP">Далее</p></div>
				</button>
			</div>
		</div>
  </a>
</div>
<script src	="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'frontend/update_quantity_ru.js' %}"></script>
  
{% endblock main %}

api/Frontend/templates/frontend/ru/pickup/events.html
{% extends 'base.html' %}
{% load static %}

{% load static %} 
{% block title %} 
{{ title }} 
{% endblock title %}

{% block main %}
<div class="HeaderWrapper">
	<button class="BackButton" style="background: transparent; top: 40px; left: 20px; box-shadow: none;">
		<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;">
			<span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;">
			</span>
      <a href="{% url 'frontend:events_and_dishes_pickup_view_ru'  %}"><i class="fa-solid fa-chevron-left fa-lg"></i></a>
		</span> 
	</button>   
	<h1>Акции</h1>
	<div class="HeaderNone"><div style="width: 48px; height: 48px;"></div></div>
</div>

{% for event in events %}
<div class="EventsBlock" data-bs-toggle="modal" data-bs-target="#exampleModal{{ forloop.counter }}">
  <div class="EventImageWrapper">
    <img src="{{ event.image }}" width="98%">
  </div>
</div>

<div class="modal fade" id="exampleModal{{ forloop.counter }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content">
      <div class="HeaderWrapper">
      <button class="BackButton" style="background: transparent; top: 40px; left: 20px; box-shadow: none;">
        <span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;">
          <span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;">
          </span>
          <a data-bs-dismiss="modal"><i class="fa-solid fa-chevron-left fa-lg"></i></a>
        </span>
      </button>   
      <div class="HeaderNone"><div style="width: 48px; height: 48px;"></div></div>
      </div>
      <div class="modal-body">
        <div class="modal-image-event">
          <img src="{{ event.image }}" alt="{{ event.title_ru }}">
        </div>
        <div class="modal-title-description-event">
          <p class="modal-description-event">{{ event.description_ru }}</p>
        </div>
        <button type="submit" class="back-to-events" data-bs-dismiss="modal">Назад</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock main %}

api/Frontend/templates/frontend/ru/pickup/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load static %} 
{% block title_ru %} 
{{ title_ru }} 
{% endblock title_ru %}

{% block main %}
<div class="ButtonBlock">
  <a href="{% url 'frontend:events_pickup_view_ru' %}" class="btn-events">
    🎊
    Акции
  </a>
  <a href="{% url 'frontend:carts_pickup_view_ru' %}" class="btn-cart">
    🛒
    Корзина
  </a>
</div>

<div class="CategoryBlock">
    <div class="NavigationWrapperLogo">
        <div class="NavigationLogoImage">
            <span style="box-sizing: border-box; display: block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: absolute; inset: 0px;">
            </span>
        </div>
    </div>
    <div class="NavigationWrapperCategories">
        {% for category in categories %}
        <a class="NavigationLink" href="{% url 'frontend:categories_pickup_view_ru'  category.id %}"><span class="NavigationTitle">{{ category.title_ru }}</span></a>
        {% endfor %}
    </div>
</div>

{% for dish in dishes %}
<div class="Cardblock" data-bs-toggle="modal" data-bs-target="#exampleModal{{ forloop.counter }}">
    <div class="CardWrapperImage" style="
      padding-right: 10px;
    ">
        <img src="{{ dish.image }}" alt="{{ dish.title_ru_ru }}">
    </div>
    <div class="CardWrapperText">
        <h3 class="Title">{{ dish.title_ru }}</h3>
        <p class="Description">{{ dish.descriptiontrim_ru }}</p>
        <div class="price"><p class="price-p">{{ dish.price}} сум</p></div>
    </div>
</div>

<div class="modal fade" id="exampleModal{{ forloop.counter }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content">
      <div class="HeaderWrapper">
        <button class="BackButton" style="background: transparent; top: 40px; left: 20px; box-shadow: none;">
          <span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;">
            <span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;">
            </span>
            <a data-bs-dismiss="modal"><i class="fa-solid fa-chevron-left fa-lg"></i></a>
          </span>
        </button>   
        <div class="HeaderNone"><div style="width: 48px; height: 48px;"></div></div>
      </div>
      <div class="modal-body">
        <div class="modal-image">
          <img src="{{ dish.image }}" alt="{{ dish.title_ru }}">
        </div>
        <div class="modal-title-description">
          <div class="modal-title-block">
              <h1 class="modal-title-h1">{{ dish.title_ru }}</h1>
          </div>
          <p class="modal-description">{{ dish.description_ru }}</p>
          <p class="modal-price" style="white-space: nowrap;">{{ dish.price }} сум</p>
      </div>
      </div>
      <form class="card-form">
        <input type="hidden" name="dish_pk" value="{{ dish.pk }}">
        <input type="hidden" name="image" value="{{ dish.image }}">
        <input type="hidden" name="title" value="{{ dish.title_ru }}">
        <input type="hidden" name="description" value="{{ dish.description_ru }}">
        <input type="hidden" name="price" value="{{ dish.price }}">
        <input type="hidden" name="category" value="{{ dish.category }}">
        <input type="hidden" name="quantity" value="{{ dish.quantity }}">
        <button type="button" class="add-to-cart-button" id="addToCartButton" data-bs-dismiss="modal">Добавить в корзину</button>
      </form>
    </div>
  </div>
</div>
{% endfor %}
{% endblock main %}

api/Frontend/templates/frontend/ru/pickup/select_time.html
{% extends 'base.html' %}
{% load static %}

{% load static %} 
{% block title %} 
{{ title }} 
{% endblock title %}

{% block main %}

<div class="HeaderWrapper">
	<button class="BackButton" style="background: transparent; top: 40px; left: 20px; box-shadow: none;">
		<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;">
			<span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;">
			</span>
			<a href="{% url 'frontend:carts_pickup_view_ru'  %}"><i class="fa-solid fa-chevron-left fa-lg"></i></a>
		</span>
	</button>   
	<h1>Выбор времени</h1>
	<div class="HeaderNone"><div style="width: 48px; height: 48px;"></div></div>
</div>

<div class="TimePicker">
	<div class="form-floating">
		<input type="time" class="form-control" id="floatingInputTime" placeholder="22:22" aria-describedby="TimeBlock">
		<label for="floatingInputTime">Время</label>
	</div>
	<div id="TimeBlock" class="form-text TextInputTime">
		Время для самовывоза.
</div>
  
<div>
    <a href="#" class="ButtonWrapperAtable">
      <div class="ButtonBlockWrapperQuantityPeople">
        <button class="ButtonWrapperQuantityPeople" style="margin: 0px; width: 100%;">
          <div class="ButtonWrapperDivQuantityPeople"><p class="TextButtonWrapperQuantityPeople TextButtonWrapperPQuantityPeople">Перейти к оплате</p></div>
        </button>
      </div>
    </a>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="{% static 'frontend/create_order_pickup.js' %}"></script>


{% endblock main %}